### ISSUE TITLE
bug: [Ionic React] IonSelect with `multiple` attribute not working as controlled component

### ISSUE THREAD

**Issue by SatoAV** [ionic-team/ionic-framework#18949]
# Bug Report

**Ionic version:**
[x] **4.7.1**
**Ionic React version:**
[x] **0.0.9**

**Current behavior:**
When using `<IonSelect>` with `multiple` attribute as a controlled component in Ionic React, i get into an infinite `setState()` loop whenever I change the value of the select.

**Expected behavior:**
`<IonSelect>` should provide the same behavior as when `multiple` attribute is not used.

**Steps to reproduce:**
1) Create a new Ionic React project from `blank` template.
2) Replace code in `/src/pages/Home.tsx` with this: https://pastebin.com/Ve5p1m9m

**Related code:**
It might be that I'm just handling `onIonChange` event wrong, but I couldn't find any proper documentation on it for React. Here is a snippet from my code above:
```
private onChange = (event: CustomEvent<SelectChangeEventDetail>) => {
    const target = event.target as HTMLInputElement;
    const value = target!.value;
    if (value) {
      const values: string[] = Array.isArray(value) ? value : [value];
      
      this.setState({ values });
    }
  }
```

**Other information:**
Error stack trace:
```
Uncaught Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at invariant (http://localhost:3000/static/js/101.chunk.js:33489:19)
    at scheduleWork (http://localhost:3000/static/js/101.chunk.js:54353:9)
    at Object.enqueueSetState (http://localhost:3000/static/js/101.chunk.js:45028:9)
    at Home.push../node_modules/react/cjs/react.development.js.Component.setState (http://localhost:3000/static/js/101.chunk.js:59598:20)
    at HTMLElement.Home._this.onChange (http://localhost:3000/static/js/main.chunk.js:596:15)
    at HTMLElement.handler (http://localhost:3000/static/js/101.chunk.js:5366:21)
    at Object.emit (http://localhost:3000/static/js/101.chunk.js:3489:18)
    at Select.valueChanged (http://localhost:3000/static/js/36.chunk.js:369:22)
    at http://localhost:3000/static/js/101.chunk.js:2923:57
    at Array.forEach (<anonymous>)
    at setValue (http://localhost:3000/static/js/101.chunk.js:2920:26)
    at HTMLElement.set [as value] (http://localhost:3000/static/js/101.chunk.js:2978:13)
    at http://localhost:3000/static/js/101.chunk.js:3018:29
    at Object.jmp (http://localhost:3000/static/js/101.chunk.js:984:12)
    at HTMLElement.prototype_1.attributeChangedCallback (http://localhost:3000/static/js/101.chunk.js:3016:15)
    at setValueForProperty (http://localhost:3000/static/js/101.chunk.js:36579:18)
    at updateDOMProperties (http://localhost:3000/static/js/101.chunk.js:41340:11)
    at updateProperties (http://localhost:3000/static/js/101.chunk.js:41748:7)
    at commitUpdate (http://localhost:3000/static/js/101.chunk.js:42656:7)
    at commitWork (http://localhost:3000/static/js/101.chunk.js:52250:17)
    at commitAllHostEffects (http://localhost:3000/static/js/101.chunk.js:53047:15)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/101.chunk.js:33579:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/101.chunk.js:33628:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/101.chunk.js:33682:35)
    at commitRoot (http://localhost:3000/static/js/101.chunk.js:53292:11)
    at http://localhost:3000/static/js/101.chunk.js:54878:9
    at Object.unstable_runWithPriority (http://localhost:3000/static/js/101.chunk.js:62705:16)
    at completeRoot (http://localhost:3000/static/js/101.chunk.js:54877:17)
    at performWorkOnRoot (http://localhost:3000/static/js/101.chunk.js:54800:13)
    at performWork (http://localhost:3000/static/js/101.chunk.js:54705:11)
    at performSyncWork (http://localhost:3000/static/js/101.chunk.js:54679:7)
    at requestWork (http://localhost:3000/static/js/101.chunk.js:54534:9)
    at scheduleWork (http://localhost:3000/static/js/101.chunk.js:54347:9)
    at Object.enqueueSetState (http://localhost:3000/static/js/101.chunk.js:45028:9)
    at Home.push../node_modules/react/cjs/react.development.js.Component.setState (http://localhost:3000/static/js/101.chunk.js:59598:20)
    at HTMLElement.Home._this.onChange (http://localhost:3000/static/js/main.chunk.js:596:15)
    at HTMLElement.handler (http://localhost:3000/static/js/101.chunk.js:5366:21)
    at Object.emit (http://localhost:3000/static/js/101.chunk.js:3489:18)
    at Select.valueChanged (http://localhost:3000/static/js/36.chunk.js:369:22)
    at http://localhost:3000/static/js/101.chunk.js:2923:57
    at Array.forEach (<anonymous>)
    at setValue (http://localhost:3000/static/js/101.chunk.js:2920:26)
    at Select.set [as value] (http://localhost:3000/static/js/101.chunk.js:2978:13)
    at handler (http://localhost:3000/static/js/36.chunk.js:685:27)
    at http://localhost:3000/static/js/101.chunk.js:3980:16
    at defaultGate (http://localhost:3000/static/js/101.chunk.js:3972:10)
    at safeCall (http://localhost:3000/static/js/101.chunk.js:3978:12)
    at Alert.callButtonHandler (http://localhost:3000/static/js/40.chunk.js:523:84)
    at Alert.buttonClick (http://localhost:3000/static/js/40.chunk.js:508:27)
    at HTMLButtonElement.onClick (http://localhost:3000/static/js/40.chunk.js:721:24)
```

**Ionic info:**
```
Ionic:
   Ionic CLI       : 5.2.3 (C:\Users\sato\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework : @ionic/react 0.0.9

Utility:
   cordova-res : not installed
   native-run  : not installed
System:
   NodeJS : v10.15.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 10
```

**Comment by themakshter** [comment]
I am also facing this issue.

**Comment by themakshter** [comment]
From what I can understand, this happens when we are setting the `value` attribute to be our `values` object. If we were to not have the `value` attribute set to this, it works fine.
