### ISSUE TITLE
bug: TypeError: i.componentOnReady is not a function

### ISSUE THREAD

**Issue by stripathix** [ionic-team/ionic-framework#20082]
# Bug Report

**Ionic version:**

```
		"@capacitor/android": "1.3.0",
		"@capacitor/cli": "1.3.0",
		"@capacitor/core": "1.3.0",
		"@capacitor/ios": "1.3.0",
		"@ionic/core": "4.11.5",
		"@ionic/vue": "0.0.9",
```

**Current behavior:**
Getting below error logged in sentry logger. Sometimes for actionSheet and sometimes for modals.
```TypeError: i.componentOnReady is not a function

StacktracE:
TypeError: i.componentOnReady is not a function
  at proxyMethod(./node_modules/@ionic/vue/dist/ionic-vue.esm.js:106:23)
  at create(./node_modules/@ionic/vue/dist/ionic-vue.esm.js:90:16)
  at apply(./src/views/Airport/Airport.js:156:18)
  at invokeWithErrorHandling(./node_modules/vue/dist/vue.runtime.esm.js:1854:26)
  at apply(./node_modules/vue/dist/vue.runtime.esm.js:2179:14)
  at apply(./node_modules/vue/dist/vue.runtime.esm.js:6911:25)
  at HTMLElement.n(./node_modules/@sentry/browser/esm/helpers.js:74:23)
```
https://sentry.io/share/issue/e389a616211442d1b5c397f7f1be5cdd/
![image](https://user-images.githubusercontent.com/8480351/70841932-908d2500-1e44-11ea-8a71-277fdff8e3c1.png)

**Expected behavior:**
Should not throw an error.

**Steps to reproduce:**
I am not able to reproduce it but it keeps getting logged to sentry from time to time.

**Related code:**
```
        openEulaModalHandle() {
            return vm.$ionic.modalController
                .create({
                    component: Eula,
                    backdropDismiss: false,
                    keyboardClose: false,
                    cssClass: "eulaModal"
                }).then(function (modalElement) {
                    modalElement.present();
                    modalElement.onDidDismiss().then(underscore.noop);
                });
        },
```

The environment in which it fails according to logs:
1) Pale moon browser.
2) Firefox v56.0
3) Chrome Mobile 52.0.2743 | Chrome Mobile | G Play | Moto G Play

**Comment by liamdebeasi** [comment]
Thanks for the issue! We recently released an all new Ionic Vue beta that should fix most of the issues reported. Can you try out the latest Ionic Vue beta and let me know if this is still an issue?



**Getting Started with the latest Ionic Vue beta**

The new Ionic Vue beta is built for Vue 3. Moving forward, we are not going to support Vue 2. For information on how to get started with the latest beta, check out our [Ionic Vue Getting Started Guide](https://ionicframework.com/docs/vue/quickstart).

At this time, we do not have a migration path from Ionic Vue built for Vue 2 to Ionic Vue built for Vue 3, but the Ionic Framework differences should be minimal.

Feel free to check out our [Ionic Vue Beta Announcement](https://ionicframework.com/blog/announcing-the-new-ionic-vue-beta/) blog post for more details on this release.



**Help! The reported issue still happens in the latest Ionic Vue beta.**

Please follow up here with the issue reproduced in an Ionic starter application running the latest Ionic Vue beta. Also include any revised steps to reproduce the issue. Issues that do not have a GitHub repo with the issue reproduced in an Ionic starter app will be closed.



**My issue is resolved/My issue is no longer relevant**.

You can either close the issue yourself, or do nothing. If there is no response within 14 days, this thread will be automatically closed.



**I have a new issue**.

Please [create a new issue](https://github.com/ionic-team/ionic-framework/issues/new/choose). Be sure to reproduce the issue in an Ionic starter application running the latest Ionic Vue beta and include a link to the repo.

Be sure to search for your issue first, as the issue you are running into may have already been reported.



We are excited to get closer to the Ionic Vue release and look forward to welcoming new Vue developers to the Ionic community. Please let me know if there are any questions. Thanks!
