### ISSUE TITLE
bug: ionic angular, karma tests not waiting for ionic to load on live-reloads

### ISSUE THREAD

**Issue by bohndthi** [ionic-team/ionic-framework#22853]
# Bug Report

**Ionic version:**
[x] **5.x**

**Current behavior:**
If a page contains an ion-segment, the karma tests throws an long error message:

```
Chrome Headless 88.0.4324.50 (Linux x86_64): Executed 2 of 111 (1 FAILED) (0 secs / 0.339 secs)
ERROR: TypeError: config.get is not a function
TypeError: config.get is not a function
    at addEventListener (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ionic/core/dist/esm/helpers-90f46169.js:29:1)
    at SegmentButton.connectedCallback (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ionic/core/dist/esm/ion-segment_2.entry.js:375:23)
    at safeCall (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ionic/core/dist/esm/index-e806d1f6.js:1261:1)
    at fireConnectedCallback (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ionic/core/dist/esm/index-e806d1f6.js:1687:1)
    at initializeComponent (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ionic/core/dist/esm/index-e806d1f6.js:1650:1)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ionic/core/dist/esm/index-e806d1f6.js:1750:1
    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-evergreen.js:368:1)
    at ProxyZoneSpec.push.QpwO.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:300:1)
    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-evergreen.js:367:1)
```

**Expected behavior:**
no long error messages
**Steps to reproduce:**

- Create new project (angular)
- add an ion-segment to a page
- run the karma unit test for the page

**Ionic info:**

@ionic/angular: 5.5.3

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you provide a GitHub repo that shows this issue happening? I have a blank starter app with an `ion-segment` and am unable to reproduce the issue.

**Comment by bohndthi** [comment]
Hey @liamdebeasi, thanks for the quick response. I now realized that the error only occurs under certain conditions:
you either have to:

- run the tests in watch mode, the error occurs at the second run and onwards
- have two `ion-segments` in your project (for example in the tabs starter app on tab1 and tab2)

i is rather complicated for me to share a project via github since i am in a corporate network. If you still have issues reproducing it, please let me now.

**Comment by liamdebeasi** [comment]
Sorry for the delay. Are you able to reproduce this in an Ionic starter app and share a link if possible? I tried adding 2 `ion-segment` instance and ran the tests in watch mode a few times, but I cannot get the error to reproduce.

**Comment by bohndthi** [comment]
Hi @liamdebeasi, please have a look at https://github.com/bohndthi/ionic-bug

**Comment by liamdebeasi** [comment]
Thanks! I can reproduce this. The issue seems to be that the tests are not waiting for Ionic Angular to be fully configured when live-reloading the Karma tests. On first test load, `config.get` is defined as well as the rest of the config, but on subsequent live-reloads, neither `config.get` nor the rest of the config seems to be setup yet.

**Comment by Spinnenzunge** [comment]
Same happens for me with ion-radio

**Comment by sunnydrall** [comment]
Is there any update?

**Comment by jordanorc** [comment]
Is there any update?

**Comment by studioromeo** [comment]
Has anyone developed a workaround to this issue?
