### ISSUE TITLE
bug:  An error occurred while running subprocess capacitor

### ISSUE THREAD

**Issue by Darren120** [ionic-team/ionic-framework#23485]
Package.json
```
{
  "name": "tabs23",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~12.0.1",
    "@angular/core": "~12.0.1",
    "@angular/forms": "~12.0.1",
    "@angular/platform-browser": "~12.0.1",
    "@angular/platform-browser-dynamic": "~12.0.1",
    "@angular/router": "~12.0.1",
    "@capacitor/android": "3.0.1",
    "@capacitor/app": "1.0.1",
    "@capacitor/core": "3.0.1",
    "@capacitor/haptics": "1.0.1",
    "@capacitor/keyboard": "1.0.1",
    "@capacitor/status-bar": "1.0.1",
    "@ionic/angular": "^5.5.2",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.0.1",
    "@angular-eslint/builder": "~12.0.0",
    "@angular-eslint/eslint-plugin": "~12.0.0",
    "@angular-eslint/eslint-plugin-template": "~12.0.0",
    "@angular-eslint/template-parser": "~12.0.0",
    "@angular/cli": "~12.0.1",
    "@angular/compiler": "~12.0.1",
    "@angular/compiler-cli": "~12.0.1",
    "@angular/language-service": "~12.0.1",
    "@capacitor/cli": "^3.0.1",
    "@ionic/angular-toolkit": "^4.0.0",
    "@ionic/app-scripts": "^3.2.4",
    "@ionic/lab": "3.2.10",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "4.16.1",
    "@typescript-eslint/parser": "4.16.1",
    "eslint": "^7.6.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "jasmine-core": "~3.7.1",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "typescript": "~4.2.4"
  },
  "description": "An Ionic project"
}
```
ionic capacitor run android --verbose

Result:
```
[capacitor]         Currently detected usages in: root project 'android', project ':app', project ':capacitor-android', ...
[capacitor]
[capacitor]         FAILURE: Build failed with an exception.
[capacitor]
[capacitor]         * What went wrong:
[capacitor]         Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
[capacitor]         > SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at 
'C:\Users\me\tabs23\android\local.properties'.
[capacitor]
[capacitor]         * Try:
[capacitor]         Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[capacitor]
[capacitor]         * Get more help at
[capacitor]         Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.https://help.gradle.org
[capacitor]
[capacitor]         Use '--warning-mode all' to show the individual deprecation warnings.  
[capacitor]         See https://docs.gradle.org/7.0/userguide/command_line_interface.html#sec:command_line_warnings
[capacitor]
[capacitor]         BUILD FAILED in 1s
[capacitor]
[capacitor]         C:\Users\me\tabs23\android>if "1" == "0" goto mainEnd
[capacitor]
[capacitor]         C:\Users\me\tabs23\android>rem Set variable GRADLE_EXIT_CONSOLE if 
you need the _script_ return code instead of
[capacitor]
[capacitor]         C:\Users\me\tabs23\android>rem the _cmd.exe /c_ return code!       
[capacitor]
[capacitor]         C:\Users\me\tabs23\android>if not "" == "" exit 1
[capacitor]
[capacitor]         C:\Users\me\tabs23\android>exit /b 1
[capacitor]
[ERROR] An error occurred while running subprocess capacitor.

        capacitor.cmd run android --target Pixel_3_API_30 exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.      
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 2 functions +1ms
  ionic:utils-process error while killing process tree for 13172: Error: Command failed: taskkill /pid 13172 /T /F
  ionic:utils-process ERROR: The process "13172" not found.
  ionic:utils-process 
  ionic:utils-process     at ChildProcess.exithandler (child_process.js:319:12)
  ionic:utils-process     at ChildProcess.emit (events.js:375:28)
  ionic:utils-process     at maybeClose (internal/child_process.js:1055:16)
  ionic:utils-process     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  ionic:utils-process   killed: false,
  ionic:utils-process   code: 128,
  ionic:utils-process   signal: null,
  ionic:utils-process   cmd: 'taskkill /pid 13172 /T /F'
  ionic:utils-process } +117ms
  ionic:utils-process onBeforeExit handler: error from function: Error: Command failed: taskkill /pid 13172 /T /F
  ionic:utils-process ERROR: The process "13172" not found.
  ionic:utils-process 
  ionic:utils-process     at ChildProcess.exithandler (child_process.js:319:12)
  ionic:utils-process     at ChildProcess.emit (events.js:375:28)
  ionic:utils-process     at maybeClose (internal/child_process.js:1055:16)
  ionic:utils-process     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  ionic:utils-process   killed: false,
  ionic:utils-process   code: 128,
  ionic:utils-process   signal: null,
  ionic:utils-process   cmd: 'taskkill /pid 13172 /T /F'
  ionic:utils-process } +3ms
  ionic:utils-process error while killing process tree for 16024: Error: Command failed: taskkill /pid 16024 /T /F
  ionic:utils-process ERROR: The process "16024" not found.
  ionic:utils-process 
  ionic:utils-process     at ChildProcess.exithandler (child_process.js:319:12)
  ionic:utils-process     at ChildProcess.emit (events.js:375:28)
  ionic:utils-process     at maybeClose (internal/child_process.js:1055:16)
  ionic:utils-process     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  ionic:utils-process   killed: false,
  ionic:utils-process   code: 128,
  ionic:utils-process   signal: null,
  ionic:utils-process   cmd: 'taskkill /pid 16024 /T /F'
  ionic:utils-process } +1ms
  ionic:utils-process onBeforeExit handler: error from function: Error: Command failed: taskkill /pid 16024 /T /F
  ionic:utils-process ERROR: The process "16024" not found.
  ionic:utils-process 
  ionic:utils-process     at ChildProcess.exithandler (child_process.js:319:12)
  ionic:utils-process     at ChildProcess.emit (events.js:375:28)
  ionic:utils-process     at maybeClose (internal/child_process.js:1055:16)
  ionic:utils-process     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  ionic:utils-process   killed: false,
  ionic:utils-process   code: 128,
  ionic:utils-process   signal: null,
  ionic:utils-process   cmd: 'taskkill /pid 16024 /T /F'
  ionic:utils-process } +2ms
  ionic:utils-process processExit: exiting (exit code: 1) +2ms
```

**Comment by Darren120** [comment]
What I tried:

Adding 
```
sdk.dir = C:\Users\me\AppData\Local\Android\Sdk
```
to loca.properties and gradle.properties
