### ISSUE TITLE
feat: Android, allow setting list of hosts (domain names/IP addresses) that are exempt from SafeBrowsing checks.

### ISSUE THREAD

**Issue by anttironty** [ionic-team/ionic-framework#24459]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already include this feature request, without success.

### Describe the Feature Request

Play-protect sometimes fails checking urls that the webview will be using, when this happens the whole webview slows down remarkably and hurts the ux massively. 

Error seen at android studio logcat:
```java
2021-12-21 15:02:11.312 1559-1627/com.example.app E/GACConnecting: GoogleApiClient connecting is in step STEP_SERVICE_BINDINGS_AND_SIGN_IN but received callback for step STEP_GETTING_REMOTE_SERVICE
    java.lang.Exception
        at lD.j(chromium-SystemWebViewGoogle.aab-stable-466410403:10)
        at lD.g(chromium-SystemWebViewGoogle.aab-stable-466410403:1)
        at uD.g(chromium-SystemWebViewGoogle.aab-stable-466410403:2)
        at bm.g(chromium-SystemWebViewGoogle.aab-stable-466410403:2)
        at wd.c(chromium-SystemWebViewGoogle.aab-stable-466410403:10)
        at qd.a(chromium-SystemWebViewGoogle.aab-stable-466410403:3)
        at rd.handleMessage(chromium-SystemWebViewGoogle.aab-stable-466410403:41)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at Dt0.dispatchMessage(chromium-SystemWebViewGoogle.aab-stable-466410403:1)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```
Related stackoverflow thread https://stackoverflow.com/questions/58725618/where-does-a-googleclientapiconnected-exception-come-from

### Describe the Use Case

When developer notices that the app suffers from this issue, setting list of hosts (domain names/IP addresses) that are exempt from SafeBrowsing checks would fix the issue.

### Describe Preferred Solution

capacitor.config.ts could have propery "safeBrowsingWhitelist" which takes list of urls that should be exempt from SafeBrowsing checks.

My current solution is to modify loadWebView in Bridge.java like this:

```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O_MR1) {
            String[] urls = {"url", "url1", "url2"};
            List<String> listOfURLs = Arrays.asList(urls);
            webView.setSafeBrowsingWhitelist(listOfURLs, null);
        }
```

### Additional Information

edit: realised that this is probably more suitable feature request to capacitor repository. Sorry about that

**Comment by sean-perkins** [comment]
@anttironty could you repost this feature request in the Capacitor repository? Unfortunately we won't be able to address that change from this repository's codebase. Thanks!
