### ISSUE TITLE
bug: ERR_OSSL_EVP_UNSUPPORTED on "ionic serve" with Node 17

### ISSUE THREAD

**Issue by leonardopaffi** [ionic-team/ionic-framework#24562]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

```
>ionic serve
  > ng.cmd run app:serve --host=localhost --port=8100
  [ng] Compiling @angular/core : es2015 as esm2015
  [ng] Compiling @angular/common : es2015 as esm2015
  [ng] Compiling @angular/platform-browser : es2015 as esm2015
  [ng] Compiling @angular/platform-browser-dynamic : es2015 as esm2015
  [ng] Compiling @angular/router : es2015 as esm2015
  [ng] Compiling @angular/forms : es2015 as esm2015
  [ng] Compiling @ionic/angular : es2015 as esm2015
  [ng] Compiling @angular/common/http : es2015 as esm2015
  [ng] - Generating browser application bundles...
  [ng] node:internal/crypto/hash:67
  [ng]   this[kHandle] = new _Hash(algorithm, xofLen);
  [ng]                   ^
  [ng] Error: error:0308010C:digital envelope routines::unsupported
  [ng]     at new Hash (node:internal/crypto/hash:67:19)
  [ng]     at Object.createHash (node:crypto:130:10)
  [ng]     at module.exports (C:\Users\user\Documents\Projects\project\app\node_modules\webpack\lib\util\createHash.js:135:53)
  [ng]     at NormalModule._initBuildHash (C:\Users\user\Documents\Projects\project\app\node_modules\webpack\lib\NormalModule.js:417:16)
  [ng]     at C:\Users\user\Documents\Projects\project\app\node_modules\webpack\lib\NormalModule.js:452:10
  [ng]     at C:\Users\user\Documents\Projects\project\app\node_modules\webpack\lib\NormalModule.js:323:13
  [ng]     at C:\Users\user\Documents\Projects\project\app\node_modules\loader-runner\lib\LoaderRunner.js:367:11
  [ng]     at C:\Users\user\Documents\Projects\project\app\node_modules\loader-runner\lib\LoaderRunner.js:172:11
  [ng]     at loadLoader (C:\Users\user\Documents\Projects\project\app\node_modules\loader-runner\lib\loadLoader.js:32:11)
  [ng]     at iteratePitchingLoaders (C:\Users\user\Documents\Projects\project\app\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
  [ng]     at iteratePitchingLoaders (C:\Users\user\Documents\Projects\project\app\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
  [ng]     at C:\Users\user\Documents\Projects\project\app\node_modules\loader-runner\lib\LoaderRunner.js:176:18
  [ng]     at loadLoader (C:\Users\user\Documents\Projects\project\app\node_modules\loader-runner\lib\loadLoader.js:47:3)
  [ng]     at iteratePitchingLoaders (C:\Users\user\Documents\Projects\project\app\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
  [ng]     at runLoaders (C:\Users\user\Documents\Projects\project\app\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
  [ng]     at NormalModule.doBuild (C:\Users\user\Documents\Projects\project\app\node_modules\webpack\lib\NormalModule.js:295:3) {
  [ng]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  [ng]   library: 'digital envelope routines',
  [ng]   reason: 'unsupported',
  [ng]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
  [ng] }
  [ng] Node.js v17.3.0
  
  [ERROR] ng has unexpectedly closed (exit code 1).
  
          The Ionic CLI will exit. Please check any output above for error details.
```

### Expected Behavior

Serving the code on the browser

### Steps to Reproduce

`>ionic serve`

### Ionic Info
```

>ionic info
[WARN] Error loading @capacitor/ios package.json: Error: Cannot find module '@capacitor/ios/package'

       Require stack:
       - C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli\lib\project\index.js
       - C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli\lib\index.js
       - C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli\index.js
       - C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli\bin\ionic

Ionic:

   Ionic CLI                     : 6.18.1 (C:\Users\user\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.9.3
   @angular-devkit/build-angular : 0.1101.4
   @angular-devkit/schematics    : 11.1.4
   @angular/cli                  : 11.1.4
   @ionic/angular-toolkit        : 3.1.1

Capacitor:

   Capacitor CLI      : 2.4.7
   @capacitor/android : 2.5.0
   @capacitor/core    : 2.4.7
   @capacitor/ios     : not installed

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v17.3.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.3.0
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. This error does not appear to be related to Ionic, so I am going to close this issue. Looking at the stack trace, this error appears to be originating from Webpack, which is a dependency in your project. I did a quick search and this appears: https://github.com/webpack/webpack/issues/14532

If you are using Webpack 5, updating Webpack should fix the issue.
If you are using Webpack 4, you will need to use a workaround: https://github.com/webpack/webpack/issues/14532#issuecomment-947515866

Node 17 uses OpenSSL 3 which is likely causing the issue: https://github.com/webpack/webpack/issues/14532#issuecomment-947807590

For additional assistance, I recommend posting a thread on the [Ionic Forum](https://forum.ionicframework.com/). Thanks!
