### ISSUE TITLE
bug: The input element's type ('number') does not support selection

### ISSUE THREAD

**Issue by rawasthi231** [ionic-team/ionic-framework#24862]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x

### Current Behavior

DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.
    at Input.valueChanged (http://localhost:3000/static/js/vendors~main.chunk.js:17165:24)
    at http://localhost:3000/static/js/vendors~main.chunk.js:53813:40
    at Array.map (<anonymous>)
    at setValue (http://localhost:3000/static/js/vendors~main.chunk.js:53810:24)
    at Input.set [as value] (http://localhost:3000/static/js/vendors~main.chunk.js:53893:13)
    at HTMLInputElement.Input.onInput (http://localhost:3000/static/js/vendors~main.chunk.js:17053:20) <ion-input name=​"punchInDistance" type=​"number" disabled=​"false" readonly=​"false" placeholder=​"Enter distance (in meters)​" class=​"form-control sc-ion-input-md-h sc-ion-input-md-s md has-focus has-value">​…​</ion-input>​ flex 

### Expected Behavior

input field should accept standard input types and values accordingly

### Steps to Reproduce

when using input type number and email, I'm facing this issue

### Ionic Info

current versions :-

"@ionic/core": "^6.0.1",
"@ionic/react": "^6.0.1",

node v14.17.4
npm 6.14.14

### Additional Information
faced this issue after reinstalling node_modules

**Comment by liamdebeasi** [comment]
Thanks for the issue. As mentioned in https://github.com/ionic-team/ionic-framework/issues/24862#issuecomment-1056905735, please upgrade to Ionic 6.0.9 to receive a fix for this.
