### ISSUE TITLE
bug: appRef.attachView is not a function

### ISSUE THREAD

**Issue by dodomui** [ionic-team/ionic-framework#25253]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

Have below error while presentToast and modal.

`Error: Uncaught (in promise): TypeError: appRef.attachView is not a function
TypeError: appRef.attachView is not a function
    at attachView (ionic-angular.js:2337:16)
    at ionic-angular.js:2292:28
    at new ZoneAwarePromise (zone.js:1349:1)
    at ionic-angular.js:2291:20
    at _ZoneDelegate.push.23484._ZoneDelegate.invoke (zone.js:409:1)
    at Object.onInvoke (core.mjs:25592:1)
    at _ZoneDelegate.push.23484._ZoneDelegate.invoke (zone.js:408:1)
    at Zone.push.23484.Zone.run (zone.js:169:1)
    at NgZone.run (core.mjs:25446:1)
    at AngularFrameworkDelegate.attachViewToDom (ionic-angular.js:2290:26)
    at framework-delegate-ce4f806c.js:9:21
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
    at asyncToGenerator.js:32:1
    at new ZoneAwarePromise (zone.js:1349:1)
    at asyncToGenerator.js:21:1
    at attachComponent (framework-delegate-ce4f806c.js:6:22)
    at ion-modal.entry.js:1194:46
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
    at asyncToGenerator.js:32:1
    at new ZoneAwarePromise (zone.js:1349:1)
    at asyncToGenerator.js:21:1
    at Modal.present (ion-modal.entry.js:1177:19)
    at index-b3eecb14.js:1612:67
    at _ZoneDelegate.push.23484._ZoneDelegate.invoke (zone.js:409:1)
    at Object.onInvoke (core.mjs:25592:1)
    at _ZoneDelegate.push.23484._ZoneDelegate.invoke (zone.js:408:1)
    at Zone.push.23484.Zone.run (zone.js:169:1)
    at zone.js:1326:1
    at _ZoneDelegate.push.23484._ZoneDelegate.invokeTask (zone.js:443:1)
    at Object.onInvokeTask (core.mjs:25579:1)
    at _ZoneDelegate.push.23484._ZoneDelegate.invokeTask (zone.js:442:1)
    at Zone.push.23484.Zone.runTask (zone.js:214:1)
    at drainMicroTaskQueue (zone.js:632:1)`

### Expected Behavior

Should able to work as previously.

### Steps to Reproduce

Previous version is working just fine. After upgraded, this problem occurred.

### Ionic Info

`Ionic:

   Ionic CLI                     : 6.19.0
   Ionic Framework               : @ionic/angular 6.1.4
   @angular-devkit/build-angular : 13.3.5
   @angular-devkit/schematics    : 13.3.5
   @angular/cli                  : 13.3.5
   @ionic/angular-toolkit        : 6.1.0

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.1
   @capacitor/ios     : 3.5.1

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   NodeJS : v16.13.0
   npm    : 8.9.0
   OS     : macOS Monterey`

**Comment by dodomui** [comment]
Just found out this error is because I trying to use alertcomponent at error tracking function

**Comment by dodomui** [comment]
close
