### ISSUE TITLE
bug: ionic cordova build android failed with "Project target does not exist"

### ISSUE THREAD

**Issue by anatoly-spb** [ionic-team/ionic-framework#25288]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

```
ionic cordova build android 
```
failed:
```
> ng.cmd run app:ionic-cordova-build --platform=android
An unhandled exception occurred: Project target does not exist.
See "C:\Users\anato\AppData\Local\Temp\ng-PnAW1P\angular-errors.log" for further details.
[[40mERROR[49m] An error occurred while running subprocess ng.
        
        ng.cmd run app:ionic-cordova-build --platform=android exited with exit code 127.
        
        Re-running this command with the --verbose flag may provide more information.
```
Here is a content of C:\Users\anato\AppData\Local\Temp\ng-PnAW1P\angular-errors.log:
```
[error] Error: Project target does not exist.
    at findProjectTarget (F:\ionic\ionic-cordova-angular\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:49:15)
    at Object.getBuilderName (F:\ionic\ionic-cordova-angular\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:62:46)
    at WorkspaceNodeModulesArchitectHost.getBuilderNameForTarget (F:\ionic\ionic-cordova-angular\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:101:35)
    at RunCommand.runSingleTarget (F:\ionic\ionic-cordova-angular\node_modules\@angular\cli\models\architect-command.js:242:55)
    at RunCommand.runArchitectTarget (F:\ionic\ionic-cordova-angular\node_modules\@angular\cli\models\architect-command.js:295:35)
    at RunCommand.run (F:\ionic\ionic-cordova-angular\node_modules\@angular\cli\commands\run-impl.js:15:25)
    at RunCommand.validateAndRun (F:\ionic\ionic-cordova-angular\node_modules\@angular\cli\models\command.js:136:33)
    at async runCommand (F:\ionic\ionic-cordova-angular\node_modules\@angular\cli\models\command-runner.js:224:24)
    at async default_1 (F:\ionic\ionic-cordova-angular\node_modules\@angular\cli\lib\cli\index.js:70:31)

```

### Expected Behavior

```
ionic cordova build android 
```
must build project successfully

### Steps to Reproduce

>ionic start ionic-cordova-angular tabs --cordova --type=angular
>cd ionic-cordova-angular
>ionic cordova resources --force
>ionic cordova platform add android
>ionic cordova build android

### Ionic Info

Ionic:

   Ionic CLI                     : 6.19.1 (C:\Tools\nvm\v16.15.0\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.1.5
   @angular-devkit/build-angular : 13.2.6
   @angular-devkit/schematics    : 13.2.6
   @angular/cli                  : 13.2.6
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 10.1.2
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 3 other plugins)

Utility:

   cordova-res : 0.15.4
   native-run  : 1.5.0

System:

   Android SDK Tools : 26.1.1 (D:\Android\sdk)
   NodeJS            : v16.15.0 (C:\Program Files\nodejs\node.exe)
   npm               : 8.5.5
   OS                : Windows 10

**Comment by anatoly-spb** [comment]
As workaround we can use:
```
npx ng add @ionic/cordova-builders
```

But what is wrong with ionic start? Why should we add it manually?

**Comment by sean-perkins** [comment]
This issue seems to be related to the Ionic CLI and should be reported here: https://github.com/ionic-team/ionic-cli/issues.

I am glad that you found a workaround, but will be closing the issue here, as this repository is for the Ionic UI components. Thanks!
