### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by MrHus** [ionic-team/ionic-framework#25334]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

I'm using React 18 in combination with @testing-library/react and @ionic/react-test-utils, and I'm getting 
the following error: `PrettyFormatPluginError: Invalid string length`.

When an assertion fails, @testing-library/react will attempt to render the `screen`. It does so by calling a library called 
`pretty-format` with a custom formatter, whose job it is to render the current screen in a human readable way.

For some reason `ionic` puts this mechanism in an infinite loop,
      
 If you manually change the `printObjectProperties` function at `node_modules/pretty-format/build/collections.js` and add some logs, you can see how many times it is called.

Also when calling `screen.debug()` you see the same behaviour.

### Expected Behavior

You expect the "screen" to be able to render when using @testing-library/react.

This did not happen in previous versions.

### Steps to Reproduce

In the reproduction repo.

Run `npm install`
Run `npm test` 

Focus the tests on the "blaat.test.tsx` file.

After waiting a long time it should print the error, for me it is about `120 seconds`.

### Code Reproduction URL

https://github.com/MrHus/ionic-react-test-fail

### Ionic Info

Ionic:

   Ionic CLI       : 6.19.1 (/Users/redacted/.nvm/versions/node/v16.15.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 6.1.6

Capacitor:

   Capacitor CLI      : 3.5.1
   @capacitor/android : 3.5.1
   @capacitor/core    : 3.5.1
   @capacitor/ios     : 3.5.1

Utility:

   cordova-res : not installed globally
   native-run  : 1.6.0

System:

   NodeJS : v16.15.0 (/Users/redacted/.nvm/versions/node/v16.15.0/bin/node)
   npm    : 8.5.5
   OS     : macOS Big Sur

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you debug this a bit more? I can reproduce this behavior, but I am not able to determine if Ionic is responsible for it. I can reproduce this using the following render code:

```jsx
<IonReactRouter>
  <IonRouterOutlet></IonRouterOutlet>
 </IonReactRouter>
```

It is possible that there is a bug in these components, or it could be that these components trigger a bug in underlying app dependency.

**Comment by liamdebeasi** [comment]
Ionic React does support React 18.

I recommend digging into what's calling `printObjectProperties`.

It looks like `printComplexValue` calls `printObjectProperties`. However `printComplexValue` also calls `printer`. The `printer` function can also call `printComplexValue`, so it looks like there is a case where infinite recursion can happen.

**Comment by MrHus** [comment]
Downgrading to `[6.0.1](https://github.com/ionic-team/ionic-framework/releases/tag/v6.0.1)` causes the problem to go away.

This is because this version lies before this change:

https://github.com/ionic-team/ionic-framework/pull/24515

Which was created because of this issue:

https://github.com/ionic-team/ionic-framework/issues/24229

I wonder if this cannot be reverted because the root cause has been fixed:

https://github.com/vitejs/vite/issues/6104

**Comment by khfy6hzy** [comment]
Hey there, is there an update on this issue? We are also bitten by this issue when upgrading to @stencilc/core v2.14.1 which introduced the `proxyCustomElement` function.

**Comment by liamdebeasi** [comment]
Were you able to reproduce the issue outside of Ionic? (I.e. in a blank Stencil app) That would help us isolate and fix the issue quicker.

**Comment by vincenthongzy** [comment]
> Were you able to reproduce the issue outside of Ionic? (I.e. in a blank Stencil app) That would help us isolate and fix the issue quicker.

I was able to reproduce using a React app bootstrapped from CRA https://github.com/vincenthongzy/stencil-repro. Please let me know if you require more details. I have exported a simple component, `<MyComponent>`  from Stencil's React bindings and the screen.debug() output is unexpected. 
<img width="518" alt="image" src="https://user-images.githubusercontent.com/107991825/175220830-9e09164f-406c-4cfe-a8e3-fcd548ddad59.png">

The above screenshot is from rendering a single `<MyComponent>`. Trying to render more than 2 <MyComponent> will cause the PrettyFormatPluginError: Invalid string length to occur.

After downgrading to `@stencil/core@2.14.0` , screen.debug() provides the expected output:

```
    <body>
      <div>
        <div
          class="App"
        >
          <header
            class="App-header"
          >
            <img
              alt="logo"
              class="App-logo"
              src="logo.svg"
            />
            <p>
              Edit 
              <code>
                src/App.js
              </code>
               and save to reload.
            </p>
            <my-component
              first="hong"
            />
            <my-component
              first="hong"
            />
            <my-component
              first="hong"
            />
            <a
              class="App-link"
              href="https://reactjs.org"
              rel="noopener noreferrer"
              target="_blank"
            >
              Learn React
            </a>
          </header>
        </div>
      </div>
    </body>
```

**Comment by liamdebeasi** [comment]
Thanks! I forwarded the repo to the Stencil team who is going to investigate further: https://github.com/ionic-team/stencil/issues/3434.

**Comment by h-sakano** [comment]
Is there any update to this Issue?
I have not been able to update from 6.0.10 because unit tests with react-testing-library are not succeeding.

**Comment by vincenthongzy** [comment]
@h-sakano you can check my reply here https://github.com/ionic-team/stencil/issues/3434#issuecomment-1219548078 to see if it helps

**Comment by tonypatton** [comment]
Any update on this issue? Seems crazy that react-testing-library and react-ionic might be broken for 6 months  and there is not a larger discussion here?

**Comment by staff0rd** [comment]
This issue is easily reproducible in a new ionic app:

1. `ionic start` > react > tabs template
2. [Change the generated test to use `getByText`](https://github.com/staff0rd/ionic-testing-framework/commit/b2c68a48235bac49cb0cd4926c8c5ddb49ce9ec2)
3. Run the test

Result:
```
 FAIL  src/App.test.tsx (18.379 s)
  ✕ renders without crashing (16800 ms)

  ● renders without crashing

    RangeError: Invalid string length

      at printObjectProperties (node_modules/pretty-format/build/collections.js:174:47)
      at printComplexValue (node_modules/pretty-format/build/index.js:310:48)
      at printer (node_modules/pretty-format/build/index.js:393:10)
      at printObjectProperties (node_modules/pretty-format/build/collections.js:173:21)
      at printComplexValue (node_modules/pretty-format/build/index.js:310:48)
      at printer (node_modules/pretty-format/build/index.js:393:10)
      at printListItems (node_modules/pretty-format/build/collections.js:141:19)
      at Object.serialize (node_modules/pretty-format/build/plugins/DOMCollection.js:62:41)
      at printPlugin (node_modules/pretty-format/build/index.js:330:16)
      at printer (node_modules/pretty-format/build/index.js:379:12)
      at printObjectProperties (node_modules/pretty-format/build/collections.js:173:21)
      at printComplexValue (node_modules/pretty-format/build/index.js:310:48)
      at printer (node_modules/pretty-format/build/index.js:393:10)
      at printObjectProperties (node_modules/pretty-format/build/collections.js:173:21)
      at printComplexValue (node_modules/pretty-format/build/index.js:310:48)
      at printer (node_modules/pretty-format/build/index.js:393:10)
      at node_modules/@testing-library/dom/dist/DOMElementFilter.js:44:79
...
```

[Here's a repo](https://github.com/staff0rd/ionic-testing-framework) where the first commit is the result of `ionic start` and the second commit is the change to `getByText`.

@vincenthongzy your reply does not solve this problem, and inspecting the result of `npm why nwsapi` we see:

```
npm why nwsapi
nwsapi@2.2.2
node_modules/nwsapi
  nwsapi@"^2.2.0" from jsdom@16.7.0
...
```

**Comment by cuzzlor** [comment]
Bump.

We're still getting this after following these instructions: https://ionic.io/blog/testing-ionic-react-apps-with-jest-and-react-testing-library and using https://github.com/ionic-team/ionic-react-test-utils

**Comment by fridgeAdmin** [comment]
I can't upgrade ionic/react from v6.0.1 because of this error. Even if I downgraded @stencil/core to v2.10.0.

**Comment by drpicox** [comment]
Still happening. I found what @staff0rd explains.

Sadly, it makes TDD/BDD a lot harder or impossible. Waiting up to 10 seconds for a test when it fails (the expected thing in TDD), without any usable error message, is not viable.

If it helps, I have added a demo repository here: 
- https://github.com/drpicox/ionic-screen-debug-fail

**Comment by staff0rd** [comment]
This is happening because [@testing-library/dom expects `constructor.name`](https://github.com/testing-library/dom-testing-library/blob/fb069c93983bc0300a6e1c91bdec5bf9443b5286/src/DOMElementFilter.ts#L198) but [@ionic/stencil](https://github.com/ionic-team/stencil/blob/main/src/compiler/transformers/decorators-to-static/component-decorator.ts) does not expose `constructor.name`.

This can be fixed in either library:
1. By [adding `constructor.name` to @ionic/stencil](https://github.com/ionic-team/stencil/compare/main...staff0rd:stencil:pretty-print). This approach would then require a rebuild of @ionic/core with that change. I'm not sure how to integrate @stencil/core updates into the @ionic/core build so I haven't tested this approach. Or;  
1. By [updating @testing-library/dom to serialize items with `constructor.is`](https://github.com/testing-library/dom-testing-library/compare/main...staff0rd:dom-testing-library:ionic-pretty-print), a property that @stencil/core _does_ expose. The package needs to be built, and [this branch includes that output](https://github.com/testing-library/dom-testing-library/compare/main...staff0rd:dom-testing-library:dist). With this approach, which I was able to test and saw this bug resolved, still has an element of complexity because @testing-library/react appears to install @testing-library/dom in its child `node_modules` folder. As such, to use this approach, the output of [dist](https://github.com/testing-library/dom-testing-library/compare/main...staff0rd:dom-testing-library:dist) needs to be copied into your project's `node_modules/@testing-library/react/node_modules/@testing-library/dom/dist` folder to resolve the bug.

I note that with approach #2, the output of `debug()` is in kebab case rather than camel case, even though we're in react:

![image](https://user-images.githubusercontent.com/6289998/224924457-db1dd5be-d72a-4c0c-a8b8-0ddce796419d.png)

**Comment by liamdebeasi** [comment]
Can everyone try the following dev build, and let me know if it resolves the issue?

```
npm install @ionic/react@7.0.0-dev.11679666496.116ae037 @ionic/react-router@7.0.0-dev.11679666496.116ae037
```

Please note that this is a dev build of Ionic 7. As a result, it is subject to the [Ionic 7 Migration Guide and Breaking Changes](https://ionicframework.com/docs/v7/updating/7-0).

**Comment by staff0rd** [comment]
@liamdebeasi I can confirm that dev build works as expected:

```typescript
import { IonSkeletonText } from '@ionic/react'
import { waitForIonicReact } from '@ionic/react-test-utils'
import { render } from '@testing-library/react'

describe('SkeletonForm', () => {
  it('should render a skeleton form', async () => {
    const { debug } = render(<IonSkeletonText />)
    await waitForIonicReact()
    debug()
  })
})
```

Result:
![image](https://user-images.githubusercontent.com/6289998/227812590-2c5def73-8a24-43cf-addb-7728f5d610d9.png)

**Comment by vmstarchenko** [comment]
> Can everyone try the following dev build, and let me know if it resolves the issue?
> 
> ```
> npm install @ionic/react@7.0.0-dev.11679666496.116ae037 @ionic/react-router@7.0.0-dev.11679666496.116ae037
> ```
> 
> Please note that this is a dev build of Ionic 7. As a result, it is subject to the [Ionic 7 Migration Guide and Breaking Changes](https://ionicframework.com/docs/v7/updating/7-0).

Everything works fine with this fix. My problem would be solved after merge.

**Comment by liamdebeasi** [comment]
Hi everyone,

The fix for this has been released in Stencil v3.2.1. Ionic has been updated to use that version, and this update should be available in an upcoming release of Ionic.
