### ISSUE TITLE
bug: Compatibility with Happy DOM

### ISSUE THREAD

**Issue by sean-perkins** [ionic-team/ionic-framework#25900]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

When testing Ionic applications with Happy DOM, the following exception is raised:

```
/Users/sean/Documents/ionic/issues/react-happy-dom/node_modules/@ionic/react/node_modules/@ionic/core/components/dir.js:24
  return (document === null || document === void 0 ? void 0 : document.dir.toLowerCase()) === 'rtl';
                                                                           ^

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at isRTL (/Users/sean/Documents/ionic/issues/react-happy-dom/node_modules/@ionic/react/node_modules/@ionic/core/components/dir.js:24:76)
    at Object.createSwipeBackGesture (/Users/sean/Documents/ionic/issues/react-happy-dom/node_modules/@ionic/react/node_modules/@ionic/core/components/swipe-back.js:19:26)
    at Object.<anonymous>.RouterOutlet.mode.connectedCallback (/Users/sean/Documents/ionic/issues/react-happy-dom/node_modules/@ionic/react/node_modules/@ionic/core/components/ion-router-outlet.js:67:124)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

This prevents developers from using Happy DOM. This also likely impacts SSR environments or other mock environments where `document.dir` is undefined. 

### Expected Behavior

Developers should be able to use happyDOM to replace JSDOM in their unit tests.

### Steps to Reproduce

1. In a starter app (e.g. React), install the preset to use Happy DOM: `npm install @happy-dom/jest-environment --save-dev`
2. Update the `test` script to use the new preset: `react-scripts test --env=@happy-dom/jest-environment --transformIgnorePatterns 'node_modules/(?!(@ionic/react|@ionic/react-router|@ionic/core|@stencil/core|ionicons)/)'`
3. Test your app `npm run test`
4. Observe: Exception is thrown regarding the `isRTL` utility

### Ionic Info

N/A

**Comment by sean-perkins** [comment]
Closing, reasoning posted here: https://github.com/ionic-team/ionic-framework/pull/25901#issuecomment-1268610645

If you are interested in this being resolved, please open a new issue. Thank you!
