### ISSUE TITLE
bug: Datepicker doesn't default to today when date provided is 'undefined'

### ISSUE THREAD

**Issue by BurkusCat** [ionic-team/ionic-framework#26170]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

- [ ] v4.x
- [ ] v5.x
- [X] v6.x
- [ ] Nightly

### Current Behavior

The date picker defaults to today, 28th May 2021 and has an error in the console.

``` js
node_modules_ionic_core_dist_esm_ion-item_8_entry_js.js:2 TypeError: Cannot destructure property 'month' of '(0 , _parse_71f28cd7_js__WEBPACK_IMPORTED_MODULE_9__.O)(...)' as it is undefined.
    at Datetime.processValue (ion-datetime_3.entry.js:696:15)
    at Datetime.componentWillLoad (ion-datetime_3.entry.js:1061:10)
    at safeCall (index-8e692445.js:1458:20)
    at dispatchHooks (index-8e692445.js:1315:23)
    at Array.dispatch (index-8e692445.js:1299:28)
    at consume (index-8e692445.js:2242:13)
    at flush (index-8e692445.js:2257:9) undefined
```

![image](https://user-images.githubusercontent.com/7528322/198076707-3f500c29-53d8-48fe-83ac-17a0c3570867.png)

### Expected Behavior

The date picker defaults to today, 26th October 2022.

![image](https://user-images.githubusercontent.com/7528322/198076801-26555289-ae11-4593-a35e-a5ee726ae2a9.png)

Some of the code docs seem to imply that if using undefined, it should try to default to today's date automatically (however, in the code even though I've passed in undefined, it is an empty string in the code throughout instead):

![image](https://user-images.githubusercontent.com/7528322/198077867-b83a18dc-a3d8-4bbb-aa87-1a7b7a9c467f.png)

### Steps to Reproduce

``` html
<ion-datetime presentation="date"
        [preferWheel]="true"
        showDefaultButtons="true"
        locale="en-GB"
        [(ngModel)]="dateValue"></ion-datetime>
```

``` ts
public dateValue: string;
```

### Ionic Info

Ionic:

   Ionic CLI                     : 6.20.1 (C:\Users\Ronan.Burke\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 6.3.2
   @angular-devkit/build-angular : 14.2.6
   @angular-devkit/schematics    : 14.2.6
   @angular/cli                  : 14.2.6
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 4.4.0
   @capacitor/android : 4.4.0
   @capacitor/core    : 4.3.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.1

System:

   NodeJS : v16.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 8.11.0
   OS     : Windows 10

**Comment by liamdebeasi** [comment]
Thanks for the report. Does this still happen in Ionic 6.3.3?

**Comment by BurkusCat** [comment]
Its fixed in Ionic 6.3.3! I'm not sure whether I should be impressed or scared of the Ionic team's ability to fix bugs just before I report them haha 😅 

Thank you very much! :)
