### ISSUE TITLE
bug: ion-nav push method not working with vanilla js

### ISSUE THREAD

**Issue by gkappel** [ionic-team/ionic-framework#27562]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

ion-nav-link work but ion-nav push method results in framework delegate missing

Uncaught (in promise) Error: framework delegate is missing
    at Object.attachComponent (framework-delegate-d2bbe945.js:15:11)
    at ViewController.init (ion-nav_2.cjs.entry.js:29:46)
    at Nav.runTransition (ion-nav_2.cjs.entry.js:511:28)
    at Nav.nextTrns (ion-nav_2.cjs.entry.js:495:10)
    at Nav.queueTrns (ion-nav_2.cjs.entry.js:440:10)
    at Nav.insertPages (ion-nav_2.cjs.entry.js:182:17)

### Expected Behavior

push should navigate to page

### Steps to Reproduce

Started with https://ionicframework.com/docs/api/nav javascript example on stackblitz

Forked and added push test
https://stackblitz.com/edit/pjgq6g?file=index.html

### Code Reproduction URL

https://stackblitz.com/edit/pjgq6g?file=index.html

### Ionic Info

[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   Ionic CLI : 7.1.1

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v16.13.1
   npm    : 8.1.2
   OS     : macOS Monterey

**Comment by gkappel** [comment]
Changing to nav.push(new (PageTwo)); appears to work,
