### ISSUE TITLE
bug: jest with Ionic angular 7.5 fails with SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by KillerCodeMonkey** [ionic-team/ionic-framework#28395]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

Jest tests are failing with:

```sh
export { getAssetPath, setAssetPath, setNonce, setPlatformOptions } from '@stencil/core/internal/client';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | import { ComponentFixture, TestBed } from '@angular/core/testing';
      2 | import { RouterModule } from '@angular/router';
    > 3 | import { IonicModule } from '@ionic/angular';
        | ^
      4 |
      5 | import { MessageComponent } from './message.component';
      6 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (src/app/message/message.component.spec.ts:3:1)
```

### Expected Behavior

jests tests are working as before 7.5

### Steps to Reproduce

1. checkout reproduction repo
2. run `npm i`
3. run `npm run test:jest src/app/message/message.component.spec.ts`

### Code Reproduction URL

https://github.com/KillerCodeMonkey/ionic-7.5-angular-jest-reproduction

### Ionic Info

```SH
Ionic:

   Ionic CLI                     : 7.1.1/cli/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.5.1
   @angular-devkit/build-angular : 16.2.7
   @angular-devkit/schematics    : 16.2.7
   @angular/cli                  : 16.2.7
   @ionic/angular-toolkit        : 9.0.0

Capacitor:

   Capacitor CLI      : 5.5.0
   @capacitor/android : not installed
   @capacitor/core    : 5.5.0
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.3

System:

   NodeJS : v18.14.0
   npm    : 9.3.1
   OS     : Linux 6.2
```

### Additional Information

It was working in ionic < 7.5.

I already found older issues for react and vue where the ionic|stencil node modules need to be excluded from transforming in jest config.

But this is not working:
```JS
{
  transformIgnorePatterns: ['node_modules/(?!(.*\\.mjs)$)', 'node_modules/(?!(@ionic/core|@stencil/core|@ionic/angular)$)'],
}
```

```SH
    import { getDebugNode, RendererFactory2 as RendererFactory2$1, InjectionToken as InjectionToken$1, ɵstringify, ɵReflectionCapabilities, Directive, Component, Pipe, NgModule, ɵgetInjectableDef, resolveForwardRef as resolveForwardRef$1, ɵNG_COMP_DEF, ɵRender3NgModuleRef, ApplicationInitStatus, LOCALE_ID as LOCALE_ID$1, ɵDEFAULT_LOCALE_ID, ɵsetLocaleId, ɵRender3ComponentFactory, ɵcompileComponent, ɵNG_DIR_DEF, ɵcompileDirective, ɵNG_PIPE_DEF, ɵcompilePipe, ɵNG_MOD_DEF, ɵtransitiveScopesFor, ɵpatchComponentDefWithScope, ɵNG_INJ_DEF, ɵcompileNgModuleDefs, provideZoneChangeDetection, Compiler, COMPILER_OPTIONS, Injector as Injector$1, ɵisEnvironmentProviders, ɵNgModuleFactory, ModuleWithComponentFactories, ɵconvertToBitFlags, InjectFlags as InjectFlags$1, ɵsetAllowDuplicateNgModuleIdsForTest, ɵresetCompiledComponents, ɵsetUnknownElementStrictMode as ɵsetUnknownElementStrictMode$1, ɵsetUnknownPropertyStrictMode as ɵsetUnknownPropertyStrictMode$1, ɵgetUnknownElementStrictMode as ɵgetUnknownElementStrictMode$1, ɵgetUnknownPropertyStrictMode as ɵgetUnknownPropertyStrictMode$1, EnvironmentInjector as EnvironmentInjector$1, NgZone as NgZone$1, ɵflushModuleScopingQueueAsMuchAsPossible } from '@angular/core';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import 'jest-preset-angular/setup-jest'
        | ^
      2 |
```

**Comment by liamdebeasi** [comment]
Thanks for the report. Your `transformIgnorePatterns` regex was slightly malformed. 

Try this instead: `transformIgnorePatterns: ['node_modules/(?!(@ionic/angular|@ionic/core|ionicons|@stencil/core|@angular/*)/)'],`

Note that I am still getting the following, but I was getting it even on Ionic 7.4.4:

```
  Cannot set base providers because it has already been called

       9 |
      10 | // First, initialize the Angular testing environment.
    > 11 | getTestBed().initTestEnvironment(
         |              ^
      12 |   BrowserDynamicTestingModule,
      13 |   platformBrowserDynamicTesting(),
      14 | );

      at _TestBedImpl.initTestEnvironment (node_modules/@angular/core/fesm2022/testing.mjs:27309:19)
      at Object.<anonymous> (src/test.ts:11:14)
```

Ionic 7.5 makes more use of ES Modules, but Jest does not have full support for ES Modules right now. Angular also uses ES Modules in your app, and your old `transformIgnorePatterns` syntax accounted for that.

**Comment by KillerCodeMonkey** [comment]
thanks @liamdebeasi 

This part:
```JS
{
  transformIgnorePatterns: ['node_modules/(?!(.*\\.mjs)$)', 'node_modules/(?!(@ionic/core|@stencil/core|@ionic/angular)$)'],
}
```

was just written out of my mind, what i tried... in real life i just forgot/did not know to add `@angular/*`. :face_with_spiral_eyes: 

Thank you! It is working :).

**Comment by KillerCodeMonkey** [comment]
@liamdebeasi i added a small readme to the repro-repo and fixed that angular's default "test.ts" is ignored by jest. It is the setup file for karma+jasmine tests.
