### ISSUE TITLE
bug: IonDatetime Angular standlone - preferWheel input is true but component presented as calendar and "Cannot redefine property: cancelText" error

### ISSUE THREAD

**Issue by PatrikHorvatic** [ionic-team/ionic-framework#28425]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

At initiating IonModal with IonDatetime component with specific configuration, IonDatetime is not presented with wheels, but as calendar. On second click it is presented as wheel picker. Also, there is an error in the console. 
```
template.html:11 ERROR TypeError: Cannot redefine property: cancelText
    at Function.defineProperty (<anonymous>)
    at ionic-angular-standalone.mjs:210:16
    at Array.forEach (<anonymous>)
    at proxyInputs (ionic-angular-standalone.mjs:209:12)
    at IonDatetime.ngOnInit (ionic-angular-standalone.mjs:2202:9)
    at callHookInternal (core.mjs:4024:14)
    at callHook (core.mjs:4051:13)
    at callHooks (core.mjs:4006:17)
    at executeInitAndCheckHooks (core.mjs:3956:9)
    at refreshView (core.mjs:13513:21)
```
[iondatetime-error-standalone.webm](https://github.com/ionic-team/ionic-framework/assets/80419964/b052a419-7f05-46cc-8569-ac230144ac60)

I have followed steps from tutorial on how to use Ionic Angular standalone with NgModules based app.

### Expected Behavior

The IonDatetime standalone component should always have wheels and not have errored.

### Steps to Reproduce

**1. Create FormDate component**
HTML:
```
<div class="form-date-kontejner input-forma-common" (click)="openPick()">
  <div class="form-date-kontejner-kalendaric">
    <ion-icon src="../../../../assets/icon/inputs/kalendaric.svg" />
  </div>
  <p class="inter fontSize14 lineHeight150 mainText ion-no-margin" *ngIf="date">{{date | date:
    'dd.MM.YYYY'}}</p>
  <p class="inter fontSize14 lineHeight150 secondaryText ion-no-margin" *ngIf="!date">
    DD/MM/YYYY</p>
</div>
<ion-modal [cssClass]="'bottom-end'" #formdatemodal [showBackdrop]="true" [backdropDismiss]="false"
  (ionModalWillPresent)="sakrijKeyboard()">
  <ng-template>
    <div class="gumbeki-pickera">
      <div class="left fontSize18" (click)="closeDatepick()">{{FORM_DATE_LANGUAGE[0] | language}}</div>
      <div class="right fontSize18 mainColor" (click)="saveDatePick()">{{FORM_DATE_LANGUAGE[1] | language}}</div>
    </div>
    <ion-datetime #datetime presentation="date" [preferWheel]="true" [(ngModel)]="date" [max]="maxDate"
      [locale]="locale" size="cover" mode="ios" [showDefaultButtons]="false" [monthValues]="monthValues"
      [dayValues]="dayValues" [yearValues]="yearValues">
    </ion-datetime>
  </ng-template>
</ion-modal>
```
CSS:
```
:host {
  position: relative;
  display: block;
  width: 100%;
  height: 50px;
  will-change: transition, transform;
}
.form-date-kontejner {
  position: relative;
  display: flex;
  justify-content: flex-start;
  align-items: center;
  width: 100%;
  height: 50px;
}
.form-date-kontejner-kalendaric {
  display: block;
  position: absolute;
  margin: 0;
  padding: 0;
  right: 15px;
  bottom: 8px;
}
.form-date-kontejner-kalendaric ion-icon {
  mask-size: contain;
  mask-position: 50% 50%;
  mask-repeat: no-repeat;
  width: 25px;
  height: 25px;
}
.gumbeki-pickera {
  display: flex;
  vertical-align: middle;
  justify-content: space-between;
  position: relative;
  width: 100%;
  height: 60px;
  color: #19bb70;
}
.left {
  margin: 15px;
}
.right {
  margin: 15px;
}
.datetime-text {
  font-family: Inter !important;
  font-size: 14px !important;
  margin-top: -3px;
}
.form-date-lijevi-dio {
  width: 80%;
  float: left;
}
.form-date-desni-dio {
  width: 20%;
  float: left;
}
ion-datetime {
  --background: white !important;
}
ion-modal {
  &.bottom-end {
    align-items: flex-end;
    --height: 250px;
  }
}
```
TypeScript
```
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output, ViewChild } from '@angular/core';
import { Keyboard } from '@capacitor/keyboard';
import { IonDatetime, IonModal } from '@ionic/angular';
import { DATETIME_PICKER_DAY_VALUES, DATETIME_PICKER_MONTH_VALUES } from 'src/app/Environment/environment';
import { logError } from 'src/app/Functions/decorators';
import { RETURN_YEARS_FOR_PICKER } from 'src/app/Functions/functions';
import { IJezici } from 'src/app/Language/language';
import { LanguageService } from 'src/app/Services/Other/language.service';

export const DATETIME_PICKER_MONTH_VALUES = [12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1];
export const DATETIME_PICKER_DAY_VALUES = [31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1];

export const RETURN_YEARS_FOR_PICKER = (): Array<number> => {
	let yearValues: Array<number> = [];

	let datum = new Date().getFullYear();
	const datumManje100 = datum - 100;
	while (datum >= datumManje100) {
		yearValues.push(datum);
		datum -= 1;
	}

	return yearValues;
};

/**Komponenta za prikaz punog datuma. Klik na komponentu otvara date picker modal. */
@Component({
  selector: 'app-form-date',
  templateUrl: './form-date.component.html',
  styleUrls: ['./form-date.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class FormDateComponent {

  @ViewChild('datetime') datetime: IonDatetime;
  @ViewChild('formdatemodal') formdatemodal: IonModal;

  @Input() date: string;
  @Input() idPicker = '1';
  @Output() dateChange: EventEmitter<string> = new EventEmitter<string>();
  @Output() callValidationInPage: EventEmitter<boolean> = new EventEmitter<boolean>();

  @Input() placeholder = '';
  @Input() disableClick = false;

  public maxDate: string;
  public dayValues = DATETIME_PICKER_DAY_VALUES;
  public monthValues = DATETIME_PICKER_MONTH_VALUES;
  public yearValues = RETURN_YEARS_FOR_PICKER();

  protected FORM_DATE_LANGUAGE: Array<IJezici> = [
    {
      hr: 'Odustani',
      en: 'Cancel',
      de: '',
      it: '',
      es: '',
      fr: ''
    },
    {
      hr: 'OK',
      en: 'OK',
      de: '',
      it: '',
      es: '',
      fr: ''
    }
  ];
  protected locale: string;

  constructor(private language: LanguageService) {
    const jezik = this.language.vratiAktivanLanguage();

    if (jezik === 'hr') {
      this.locale = 'hr-HR';
    }
    else if (jezik === 'en') {
      this.locale = 'en-US';
    }
  }

  @logError
  sakrijKeyboard() {
    Keyboard.hide();
  }

  @logError
  Change() {
    this.dateChange.emit(this.date);
  }

  @logError
  openPick() {
    this.formdatemodal.present();
  }

  @logError
  closeDatepick() {
    this.formdatemodal.dismiss();
    this.datetime.cancel();
  }

  @logError
  saveDatePick() {
    this.datetime.confirm(true)
      .then(() => {
        this.dateChange.emit(this.date);
      })
      .catch(() => {
      });
    // this.formdatemodal.dismiss();
  }
}

```

**2. Created component add to respected NgModule with proper standalone inputs:**
```
import { DatePipe, NgClass, NgIf } from '@angular/common';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { IonDatetime, IonIcon, IonModal } from '@ionic/angular/standalone';
import { LanguagePipeModule } from 'src/app/Pipes/Language/LanguagePipe.module';
import { FormDateComponent } from './form-date/form-date.component';

@NgModule({
    declarations: [FormDateComponent],
    imports: [IonModal, IonDatetime, IonIcon,
        NgIf, NgClass, DatePipe, FormsModule, LanguagePipeModule],
    exports: [FormDateComponent]
})
export class FormDateComponentModule { }
```

3. Add FormDateComponentModule to page module. Add component to page template:
```
<ion-content [scrollY]="false" [scrollX]="false">
    <app-form-date [(date)]="birthDate" />
</ion-content>
```

**4. Click on app-form-date component. An error should occour and be printed in the console. Also, there is a chance that IonDatetime will NOT be presented as wheel picker but as calendar, as demonstrated in the video.**

### Ionic Info

**Ionic:**

   Ionic CLI                     : 7.1.1 (C:\Users\patrik.horvatic\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 7.5.2
   @angular-devkit/build-angular : 16.2.8
   @angular-devkit/schematics    : 16.2.8
   @angular/cli                  : 16.2.8
   @ionic/angular-toolkit        : 10.0.0

**Capacitor:**

   Capacitor CLI      : 5.5.1
   @capacitor/android : 5.5.1
   @capacitor/core    : 5.5.1
   @capacitor/ios     : 5.5.1

**Utility:**

   cordova-res : 0.15.4
   native-run  : 1.7.3

**System:**

   NodeJS : v18.12.0 (C:\Program Files\nodejs\node.exe)
   npm    : 9.6.6
   OS     : Windows 10

### Additional Information

I have also submited similar error with IonCheckbox Angular standalone component (https://github.com/ionic-team/ionic-framework/issues/28418) which I think You have solved. They are probably related since an error was found in one of StencilJS utility functions.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic-framework/issues/28418, and a fix will be available in an upcoming release of Ionic Framework. This is indeed the same problem 😄
