### ISSUE TITLE
bug: ion-range throws: Cannot read properties of undefined.

### ISSUE THREAD

**Issue by fudom** [ionic-team/ionic-framework#29667]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/docs/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v8.x

### Current Behavior

Since the latest Ionic version v8 (coming from Ionic 6), the ion-range throws errors.

```
TypeError: Cannot read properties of undefined (reading 'toString')
  at getDecimalPlaces (ion-range.entry.js:15:14)
  at ion-range.entry.js:50:57
  at Array.map (<anonymous>)
  at roundToMaxDecimalPlaces (ion-range.entry.js:50:46)
  at ratioToValue (ion-range.entry.js:666:12)
  at get valA (ion-range.entry.js:394:16)
  at Range.renderRangeSlider (ion-range.entry.js:479:22)
  at Range.render (ion-range.entry.js:615:300)
```

This error occurs at least on Angular. I think it's because following:

- Set value: Call `updateRatio`: min/max possible undefined
- Set min: Call `updateRatio`: max/value possible undefined
- Set max: Call `updateRatio`: min/value possible undefined

This results in runtime error and invisible range component. It's maybe because a framework like Angular creates the attibutes for binding even if the value is not yet ready. In this case, it's undefined first. But idk. Anyway, it would be a good practice to treat undefined, wouldn't it?

### Expected Behavior

Handle `undefined`. It's possible that one value can be undefined.

### Steps to Reproduce

```html
<ion-item *ngIf="hasRange()">
  <ion-range [(ngModel)]="value" [min]="min" [max]="max"></ion-range>
</ion-item>
```

All values are inputs (`Input` Angular decorator). The `hasRange` method returns true if both values (min, max) are available (not undefined) and not equal (min !== max).

In my case I created a modal with componentProps which goes to Angular component inputs.

NOTE: I already catch undefined values. It seems that this problem comes from Ionic framework.

### Code Reproduction URL

https://codepen.io/fudom/pen/ZENZxdq
But not really good reproducible in a playground. Just handle undefined values!

### Ionic Info

[Ionic Angular](https://www.npmjs.com/package/@ionic/angular) 8.2.3

### Additional Information

- [docs](https://ionicframework.com/docs/api/range)
- [range.tsx](https://github.com/ionic-team/ionic-framework/blob/52ff0505e86dc204cb2fd2fdaf67229e6eeb36f8/core/src/components/range/range.tsx)
- [utils/floating-point](https://github.com/ionic-team/ionic-framework/blob/52ff0505e86dc204cb2fd2fdaf67229e6eeb36f8/core/src/utils/floating-point/index.ts)

**Comment by brandyscarney** [comment]
Thank you for reporting the issue! Could you please reproduce the problem in a StackBlitz example for us? I've created one that you can use: https://stackblitz.com/edit/angular-wx2c3i?file=src%2Fapp%2Fmodal-example.component.ts

In the top left of the StackBlitz example, you can `Fork` the project, make the necessary changes to reproduce the error, then `Save` it and `Share` the link with me. This will help us resolve the issue. Thank you!

**Comment by ShaneK** [comment]
Thank you for the issue report, reproduction, and PR. We've merged in your PR after minor adjustment and this issue will be addressed with the next release.
