### ISSUE TITLE
Toast - `getButtons()` function type check error

### ISSUE THREAD

**Issue by NickSuomi** [ionic-team/ionic-framework#29976]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@ionic/core@8.3.2` for the project I'm working on.

```log
{
arguments: [{"message":"this.buttons.map is not a function","name":"TypeError","stack":"TypeError: this.buttons.map is not a function\n at gi.overlayIndex.getButtons (https:\/\/localhost\/assets\/index-ZavtgWYp.js:215:15636)\n at gi.overlayIndex.render (https:\/\/localhost\/assets\/index-ZavtgWYp.js:215:17411)\n at Vyt (https:\/\/localhost\/assets\/index-ZavtgWYp.js:18:28880)\n at https:\/\/localhost\/assets\/index-ZavtgWYp.js:18:28801\n at Generator.next (<anonymous>)\n at https:\/\/localhost\/assets\/index-ZavtgWYp.js:2:1259\n at new Promise (<anonymous>)\n at M (https:\/\/localhost\/assets\/index-ZavtgWYp.js:2:1079)\n at Hyt (https:\/\/localhost\/assets\/index-ZavtgWYp.js:18:28651)\n at https:\/\/localhost\/assets\/index-ZavtgWYp.js:18:28511\n at K6e (https:\/\/localhost\/assets\/index-ZavtgWYp.js:18:28568)\n at Byt (https:\/\/localhost\/assets\/index-ZavtgWYp.js:18:28501)\n at Array.<anonymous> (https:\/\/localhost\/assets\/index-ZavtgWYp.js:18:27996)\n at H6e (https:\/\/localhost\/assets\/index-ZavtgWYp.js:18:16464)\n at VDe (https:\/\/localhost\/assets\/index-ZavtgWYp.js:18:16529)\n at r (https:\/\/localhost\/assets\/index-ZavtgWYp.js:309:5509)"},{"didPresent":{"emit":"[Function: emit]"},"willPresent":{"emit":"[Function: emit]"},"willDismiss":{"emit":"[Function: emit]"},"didDismiss":{"emit":"[Function: emit]"},"didPresentShorthand":{"emit":"[Function: emit]"},"willPresentShorthand":{"emit":"[Function: emit]"},"willDismissShorthand":{"emit":"[Function: emit]"},"didDismissShorthand":{"emit":"[Function: emit]"},"delegateController":{"attachViewToDom":"[Function: attachViewToDom]","removeViewFromDom":"[Function: removeViewFromDom]"},"lockController":{"lock":"[Function: lock]"},"triggerController":{"addClickListener":"[Function: addClickListener]","removeClickListener":"[Function: t]"},"customHTMLEnabled":true,"presented":false,"dispatchCancelHandler":"[Function: <anonymous>]","createSwipeGesture":"[Function: <anonymous>]","destroySwipeGesture":"[Function: <anonymous>]","p...
}
```

Context code:

```ts
  const newShowToast = async (
    id: string,
    message: string,
    isSuccess: boolean,
    sentryDetails?: ErrorEvent | null,
    serverDetails?: ResponseErrorModel | null
  ): Promise<void> => {
    toastController.getTop().then((t) => {
      if (t) {
        if (t.id === id || t.message === message) {
          t.dismiss();
        } else {
          movedToastTo =
            document.getElementById(`${t.id}`)?.shadowRoot?.querySelector('.toast-wrapper')?.getBoundingClientRect()
              .height || movedToastTo;
        }
      }
    });

    let toastButtons: ToastButton[] = [
      {
        text: '',
        icon: linkOutline,
        role: 'link',
        side: 'end',
        handler: async () => {
          const link = sentryDetails?.event_id ?? serverDetails?.traceId ?? new Date().toISOString();
          if (isAnyMobile) {
            await nativeClipboard.write({ string: link });
          } else {
            navigator.clipboard.writeText(link);
          }

          await toast.dismiss();
        },
      },
      {
        text: '',
        icon: copyOutline,
        role: 'copy',
        side: 'end',
        handler: async () => {
          const string = `[${JSON.stringify(sentryDetails, null, 2)},\n${JSON.stringify(serverDetails, null, 2)}]`;
          if (isAnyMobile) {
            await nativeClipboard.write({ string });
          } else {
            navigator.clipboard.writeText(string);
          }

          await toast.dismiss();
        },
      },
      {
        text: '',
        icon: closeCircleOutline,
        role: 'close',
        side: 'end',
        handler: async () => {
          await toast.dismiss();
        },
      },
    ];

    if (!isDev) {
      toastButtons = toastButtons.pop() as ToastButton[];
    }

    const toast = await toastController.create({
      id: id,
      mode: 'md',
      message: message,
      duration: isSuccess ? 3000 : 0,
      animated: true,
      position: 'top',
      icon: isSuccess ? checkmarkOutline : warningOutline,
      cssClass: ['custom_toast', isSuccess ? 'success' : 'fail'],
      buttons: toastButtons,
    });

    toast.addEventListener('ionToastWillPresent', async () => {
      if (movedToastTo) {
        toast.style.marginTop = `${movedToastTo + 10}px`;
      }
    });
    toast.addEventListener('ionToastWillDismiss', _resetCurrentError);

    await toast.present();
  };
```

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@ionic/core/dist/cjs/ion-toast.cjs.entry.js b/node_modules/@ionic/core/dist/cjs/ion-toast.cjs.entry.js
index 8d452c4..5f69b15 100644
--- a/node_modules/@ionic/core/dist/cjs/ion-toast.cjs.entry.js
+++ b/node_modules/@ionic/core/dist/cjs/ion-toast.cjs.entry.js
@@ -710,10 +710,8 @@ const Toast = class {
         return overlays.eventMethod(this.el, 'ionToastWillDismiss');
     }
     getButtons() {
-        const buttons = this.buttons
-            ? this.buttons.map((b) => {
-                return typeof b === 'string' ? { text: b } : b;
-            })
+        const buttons = this.buttons && Array.isArray(this.buttons)
+            ? this.buttons.map((b) => (typeof b === 'string' ? { text: b } : b))
             : [];
         return buttons;
     }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by tanner-reits** [comment]
@NickSuomi The `buttons` prop for a toast element should only be a string or `ToastButton` array. In your code, there is a chunk that will violate those types:

```
if (!isDev) {
  toastButtons = toastButtons.pop() as ToastButton[];
}
``` 

`pop()` returns a single element. So for the component logic to work as expected you need to wrap that in an array:

```
if (!isDev) {
  toastButtons = [toastButtons.pop()] as ToastButton[];
}
```
